from datetime import datetime, timezone

feed_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>My RSS Feed</title>
<link>https://YOUR-GITHUB-USERNAME.github.io/YOUR-REPOSITORY/</link>
<description>Automatically generated RSS feed</description>

<item>
<title>Feed Generated Successfully</title>
<description>This feed was generated by GitHub Actions.</description>
<pubDate>{datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S GMT")}</pubDate>
</item>

</channel>
</rss>
"""

with open("feed.xml", "w", encoding="utf-8") as file:
    file.write(feed_content)

print("feed.xml generated successfully")
